[package]
name = "todolist"
version = "0.1.0"
authors = ["Robby <ta7382@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7.14"
env_logger = "0.6.0"
log = "0.4.6"
serde_json = "1.0.33"
serde_derive = "1.0.80"
serde = "1.0.80"
